name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 194.182.81.44
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/magicspace
            git pull origin main
            sudo systemctl restart magicspace
